server:
  port: 0

spring:
  application:
    name: user-service
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      sql_comments: true
      dialect: org.hibernate.dialect.MySQL8Dialect
      id.new_generator_mappings: false
      physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

token:
  expiration_time: 86400000
  secret: user_token

#logging:
#  level:
#    root: debug

