server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/donghyeun/Desktop/Java/msa-practice/config-files
          default-label: master

